# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ui_files\DialogProductType.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogProductType(object):
    def setupUi(self, DialogProductType):
        DialogProductType.setObjectName("DialogProductType")
        DialogProductType.resize(256, 222)
        self.formLayoutWidget = QtWidgets.QWidget(DialogProductType)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 231, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cb_mainCat = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_mainCat.setObjectName("cb_mainCat")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_mainCat)
        self.cb_secondCat = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_secondCat.setObjectName("cb_secondCat")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_secondCat)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cb_status = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_status.setObjectName("cb_status")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_status)
        self.txt_productType = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_productType.setObjectName("txt_productType")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_productType)
        self.btn_save = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btn_save)
        self.lbl_title = QtWidgets.QLabel(DialogProductType)
        self.lbl_title.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_title.setFont(font)
        self.lbl_title.setText("")
        self.lbl_title.setObjectName("lbl_title")

        self.retranslateUi(DialogProductType)
        QtCore.QMetaObject.connectSlotsByName(DialogProductType)

    def retranslateUi(self, DialogProductType):
        _translate = QtCore.QCoreApplication.translate
        DialogProductType.setWindowTitle(_translate("DialogProductType", "Form"))
        self.label.setText(_translate("DialogProductType", "Üst Grup :"))
        self.label_4.setText(_translate("DialogProductType", "Alt Grup :"))
        self.label_2.setText(_translate("DialogProductType", "Malzeme Cins :"))
        self.label_3.setText(_translate("DialogProductType", "Durum :"))
        self.btn_save.setText(_translate("DialogProductType", "Kaydet"))
